// assets/javascript/pegasus/examples/react/EmployeeTableRow.js
import React from "react";
import {Link} from "react-router-dom";

const EmployeeTableRow = function (props) {
  const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  });
  return (
    <tr>
      <td>{props.name}</td>
      <td>{props.department}</td>
      <td className="pg-text-right">{ formatter.format(props.salary) }</td>
      <td className="pg-inline-buttons pg-justify-content-end">
          <Link to={`/edit/${props.id}`}>
            <div className="pg-button-secondary">
              <span className="icon is-small"><i className="fa fa-edit" /></span>
              <span className="pg-hidden-mobile-inline">Edit</span>
            </div>
          </Link>
          <a style={{'marginLeft': '1em'}} onClick={() => props.delete(props.index)}>
            <div className="pg-button-danger">
              <span className="icon is-small"><i className="fa fa-times" /></span>
              <span className="pg-hidden-mobile-inline">Delete</span>
            </div>
          </a>
      </td>
    </tr>
  );
}

export default EmployeeTableRow;

// assets/javascript/pegasus/examples/vue/components/EmployeeTableRow.vue
<template>
  <tr>
    <td>{{ employee.name }}</td>
    <td>{{ employee.department }}</td>
    <td class="pg-text-right">{{ formattedSalary }}</td>
    <td class="pg-inline-buttons pg-justify-content-end">
      <a class="pg-button-secondary" v-on:click="editEmployee">
        <span class="icon is-small"><i class="fa fa-edit" /></span>
        <span class="pg-hidden-mobile-inline">Edit</span>
      </a>
      <a class="pg-button-danger mx-2" v-on:click="deleteEmployee">
        <span class="icon is-small"><i class="fa fa-times" /></span>
        <span class="pg-hidden-mobile-inline">Delete</span>
      </a>
    </td>
  </tr>
</template>

<script>

export default {
  name: 'EmployeeTableRow',
  props: {
    employee: Object,
    client: Object,
  },
  computed: {
    formattedSalary: function () {
      const formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
      });
      return formatter.format(this.employee.salary);
    }
  },
  methods: {
    editEmployee: function () {
      this.$emit('edit-employee', this.employee);
    },
    deleteEmployee: function () {
      this.$emit('delete-employee', this.employee);
    },
  }
};
</script>

<style scoped>
</style>
